# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streamcount_pb2 as streamcount__pb2


class StreamCounterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Count = channel.stream_unary(
                '/streamcount.StreamCounter/Count',
                request_serializer=streamcount__pb2.CountRequest.SerializeToString,
                response_deserializer=streamcount__pb2.CountReply.FromString,
                )


class StreamCounterServicer(object):
    """The greeting service definition.
    """

    def Count(self, request_iterator, context):
        """Send users and count unique names
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamCounterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Count': grpc.stream_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=streamcount__pb2.CountRequest.FromString,
                    response_serializer=streamcount__pb2.CountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamcount.StreamCounter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamCounter(object):
    """The greeting service definition.
    """

    @staticmethod
    def Count(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/streamcount.StreamCounter/Count',
            streamcount__pb2.CountRequest.SerializeToString,
            streamcount__pb2.CountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
